{% set name = "erddapy" %}
{% set version = "2.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/erddapy-{{ version }}.tar.gz
  sha256: 0206dcba3954340281a9e283d9bc3925581205492531d98775c65a61cb23bb90

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=42
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.10
    - httpx
    - pandas <3,>=0.25.2
    - pytz

test:
  imports:
    - erddapy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyoceans/erddapy
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Python interface for ERDDAP

extra:
  recipe-maintainers:
    - ocefpaf
