{% set version = "0.1.2" %}

package:
  name: erddapy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/erddapy/erddapy-{{ version }}.tar.gz
  sha256: b3138bb23108bea470179c1c8b6bbf5006322975e36fe67738eda06e5da892e6

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pandas
    - requests

test:
  imports:
    - erddapy

about:
  home: https://github.com/ocefpaf/erddapy
  license: BSD 3-Clause
  summary: 'Python interface for ERDDAP'

extra:
  recipe-maintainers:
    - ocefpaf
