{% set version = "0.6.0" %}

package:
  name: erddapy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/erddapy/erddapy-{{ version }}.tar.gz
  sha256: 142fe4fd1af74d10785a245a43b6b4793f723169d4db9ceeb6f0b337b80461d0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6,<4
    - pip
    - setuptools_scm
  run:
    - python >=3.6,<4
    - pandas >=0.20.3
    - requests

test:
  requires:
    - pip
  imports:
    - erddapy
  commands:
    - pip check

about:
  home: https://github.com/pyoceans/erddapy
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Python interface for ERDDAP

extra:
  recipe-maintainers:
    - ocefpaf
